### ISSUE TITLE
Support per namespace Secrets. It will help to have different config on different environment

### ISSUE THREAD

**Issue by Harsh0** [okteto/cloud-feedback#66]

**Comment by pchico83** [comment]
@Harsh0 what is your use case for having different configurations per namespace?

**Comment by davemaier** [comment]
I just came up with the same requirement and I can describe my use case. 
 I want to use okteto pipelines for deployment and I want to deploy the same application to multiple namespaces. Since my namespaces represent different environments and I'm using okteto secrets that are environment dependent in my pipeline (different DB connections for instance) I need the ability to have multiple secrets with the same name, but for different namespaces.
 
 Another possiblity to solve this would be to specify a environment for a secret (prod, stage, dev) and give the possibility to add some kind of environment setting to each namespace so the correct secrets are available. 
 
 A good example for this is the secret management at vercel.

**Comment by pchico83** [comment]
@davemaier we want to support secrets at the application level, and secrets at the namespace level, but the current plan is to implement them at the application level first. 
By application I mean one (or more) git repos that you can create as a template, with its own secrets and setting the branches you want to deploy. When deploying, it will possible to modify these application secrets/branches.
Would that cover your use case?

**Comment by davemaier** [comment]
Thanks for your answer @pchico83. As far as I understoot it should be possible to define secrets per pipeline that gets deployed, meaning that I can specify different secrets for different branches. That would meet my usecase even better than setting secrets on namespace level.

**Comment by pchico83** [comment]
@davemaier environment variables at deployment time are now available in Cloud

**Comment by pchico83** [comment]
We are archiving this repo in favor of our [community site](https://community.okteto.com/).
Please, open your issues/feature requests there.
Thanks!
